# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4
pr:
 - none
 
trigger:
 - master

pool:
  vmImage:  'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

# - task: DotNetCoreCLI@2
#   displayName: 'Build'
#   inputs:
#     command: 'build'
#     projects: '$(solution)'

- bash: fc-list
- bash: ls /etc/fonts/
- bash: ls /usr/share/fonts/type1 && ls /usr/share/fonts/cmap && ls /usr/share/fonts/cMap && ls /usr/share/fonts/truetype
- bash: ls /usr/share/fonts/type1/lato 
- bash: ls /usr/share/fonts/cmap/lato 
- bash: ls /usr/share/fonts/cMap/lato
- bash: ls /usr/share/fonts/truetype/lato

# - task: DotNetCoreCLI@2
#   displayName: 'Test'
#   inputs:
#     command: 'test'
#     projects: '$(solution)'

# # - task: DotNetCoreCLI@2
  # # displayName: 'Packing CrossCutting packages'
  # # inputs:
    # # command: 'pack'
    # # packagesToPack: '$(solution)'
    # # versioningScheme: 'off'

# # - task: NuGetCommand@2
  # # displayName: 'Publish packages'
  # # inputs:
    # # command: 'push'
    # # packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    # # nuGetFeedType: 'internal'
    # # publishVstsFeed: 'b6656621-f150-458d-b63e-2e2b853337e7'
    # # allowPackageConflicts: true

